In [24]:
import requests
import defs
import pandas as pd

In [2]:
session = requests.Session()

In [3]:
instrument = "EUR_USD"
count = 10
granularity = "H1"

In [4]:
url = f"{defs.OANDA_URL}/instruments/{instrument}/candles"

In [5]:
url

'https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles'

In [6]:
params = dict(
    count = count,
    granularity = granularity,
    price = "MBA"
)

In [7]:
params

{'count': 10, 'granularity': 'H1', 'price': 'MBA'}

In [8]:
response = session.get(url, params=params, headers=defs.SECURE_HEADER)

In [9]:
response.status_code

200

In [10]:
response.json()

{'instrument': 'EUR_USD',
 'granularity': 'H1',
 'candles': [{'complete': True,
   'volume': 2792,
   'time': '2024-02-02T12:00:00.000000000Z',
   'bid': {'o': '1.08831', 'h': '1.08844', 'l': '1.08769', 'c': '1.08797'},
   'mid': {'o': '1.08838', 'h': '1.08852', 'l': '1.08776', 'c': '1.08804'},
   'ask': {'o': '1.08845', 'h': '1.08859', 'l': '1.08784', 'c': '1.08811'}},
  {'complete': True,
   'volume': 11299,
   'time': '2024-02-02T13:00:00.000000000Z',
   'bid': {'o': '1.08800', 'h': '1.08854', 'l': '1.08031', 'c': '1.08064'},
   'mid': {'o': '1.08807', 'h': '1.08861', 'l': '1.08038', 'c': '1.08072'},
   'ask': {'o': '1.08814', 'h': '1.08868', 'l': '1.08045', 'c': '1.08079'}},
  {'complete': True,
   'volume': 11472,
   'time': '2024-02-02T14:00:00.000000000Z',
   'bid': {'o': '1.08067', 'h': '1.08163', 'l': '1.07908', 'c': '1.08078'},
   'mid': {'o': '1.08074', 'h': '1.08170', 'l': '1.07916', 'c': '1.08089'},
   'ask': {'o': '1.08081', 'h': '1.08178', 'l': '1.07923', 'c': '1.08100'}},
  {'complete': True,
   'volume': 10559,
   'time': '2024-02-02T15:00:00.000000000Z',
   'bid': {'o': '1.08070', 'h': '1.08106', 'l': '1.07824', 'c': '1.08017'},
   'mid': {'o': '1.08078', 'h': '1.08113', 'l': '1.07831', 'c': '1.08024'},
   'ask': {'o': '1.08085', 'h': '1.08124', 'l': '1.07838', 'c': '1.08031'}},
  {'complete': True,
   'volume': 6530,
   'time': '2024-02-02T16:00:00.000000000Z',
   'bid': {'o': '1.08019', 'h': '1.08031', 'l': '1.07817', 'c': '1.07854'},
   'mid': {'o': '1.08026', 'h': '1.08038', 'l': '1.07824', 'c': '1.07862'},
   'ask': {'o': '1.08033', 'h': '1.08045', 'l': '1.07831', 'c': '1.07869'}},
  {'complete': True,
   'volume': 5032,
   'time': '2024-02-02T17:00:00.000000000Z',
   'bid': {'o': '1.07855', 'h': '1.07919', 'l': '1.07800', 'c': '1.07827'},
   'mid': {'o': '1.07863', 'h': '1.07926', 'l': '1.07808', 'c': '1.07834'},
   'ask': {'o': '1.07871', 'h': '1.07933', 'l': '1.07815', 'c': '1.07842'}},
  {'complete': True,
   'volume': 4502,
   'time': '2024-02-02T18:00:00.000000000Z',
   'bid': {'o': '1.07828', 'h': '1.07905', 'l': '1.07797', 'c': '1.07875'},
   'mid': {'o': '1.07836', 'h': '1.07912', 'l': '1.07805', 'c': '1.07883'},
   'ask': {'o': '1.07844', 'h': '1.07920', 'l': '1.07813', 'c': '1.07891'}},
  {'complete': True,
   'volume': 3232,
   'time': '2024-02-02T19:00:00.000000000Z',
   'bid': {'o': '1.07874', 'h': '1.07952', 'l': '1.07854', 'c': '1.07918'},
   'mid': {'o': '1.07882', 'h': '1.07959', 'l': '1.07862', 'c': '1.07926'},
   'ask': {'o': '1.07889', 'h': '1.07966', 'l': '1.07869', 'c': '1.07934'}},
  {'complete': True,
   'volume': 2937,
   'time': '2024-02-02T20:00:00.000000000Z',
   'bid': {'o': '1.07919', 'h': '1.07967', 'l': '1.07913', 'c': '1.07925'},
   'mid': {'o': '1.07926', 'h': '1.07974', 'l': '1.07920', 'c': '1.07932'},
   'ask': {'o': '1.07933', 'h': '1.07982', 'l': '1.07928', 'c': '1.07939'}},
  {'complete': True,
   'volume': 1975,
   'time': '2024-02-02T21:00:00.000000000Z',
   'bid': {'o': '1.07924', 'h': '1.07934', 'l': '1.07819', 'c': '1.07844'},
   'mid': {'o': '1.07932', 'h': '1.07942', 'l': '1.07854', 'c': '1.07870'},
   'ask': {'o': '1.07939', 'h': '1.07950', 'l': '1.07874', 'c': '1.07897'}}]}

In [11]:
data = response.json()

In [12]:
data.keys()

dict_keys(['instrument', 'granularity', 'candles'])

In [13]:
len(data['candles'])

10

In [15]:
for candle in data['candles']:
    print(candle)

{'complete': True, 'volume': 2792, 'time': '2024-02-02T12:00:00.000000000Z', 'bid': {'o': '1.08831', 'h': '1.08844', 'l': '1.08769', 'c': '1.08797'}, 'mid': {'o': '1.08838', 'h': '1.08852', 'l': '1.08776', 'c': '1.08804'}, 'ask': {'o': '1.08845', 'h': '1.08859', 'l': '1.08784', 'c': '1.08811'}}
{'complete': True, 'volume': 11299, 'time': '2024-02-02T13:00:00.000000000Z', 'bid': {'o': '1.08800', 'h': '1.08854', 'l': '1.08031', 'c': '1.08064'}, 'mid': {'o': '1.08807', 'h': '1.08861', 'l': '1.08038', 'c': '1.08072'}, 'ask': {'o': '1.08814', 'h': '1.08868', 'l': '1.08045', 'c': '1.08079'}}
{'complete': True, 'volume': 11472, 'time': '2024-02-02T14:00:00.000000000Z', 'bid': {'o': '1.08067', 'h': '1.08163', 'l': '1.07908', 'c': '1.08078'}, 'mid': {'o': '1.08074', 'h': '1.08170', 'l': '1.07916', 'c': '1.08089'}, 'ask': {'o': '1.08081', 'h': '1.08178', 'l': '1.07923', 'c': '1.08100'}}
{'complete': True, 'volume': 10559, 'time': '2024-02-02T15:00:00.000000000Z', 'bid': {'o': '1.08070', 'h': '1.08106', 'l': '1.07824', 'c': '1.08017'}, 'mid': {'o': '1.08078', 'h': '1.08113', 'l': '1.07831', 'c': '1.08024'}, 'ask': {'o': '1.08085', 'h': '1.08124', 'l': '1.07838', 'c': '1.08031'}}
{'complete': True, 'volume': 6530, 'time': '2024-02-02T16:00:00.000000000Z', 'bid': {'o': '1.08019', 'h': '1.08031', 'l': '1.07817', 'c': '1.07854'}, 'mid': {'o': '1.08026', 'h': '1.08038', 'l': '1.07824', 'c': '1.07862'}, 'ask': {'o': '1.08033', 'h': '1.08045', 'l': '1.07831', 'c': '1.07869'}}
{'complete': True, 'volume': 5032, 'time': '2024-02-02T17:00:00.000000000Z', 'bid': {'o': '1.07855', 'h': '1.07919', 'l': '1.07800', 'c': '1.07827'}, 'mid': {'o': '1.07863', 'h': '1.07926', 'l': '1.07808', 'c': '1.07834'}, 'ask': {'o': '1.07871', 'h': '1.07933', 'l': '1.07815', 'c': '1.07842'}}
{'complete': True, 'volume': 4502, 'time': '2024-02-02T18:00:00.000000000Z', 'bid': {'o': '1.07828', 'h': '1.07905', 'l': '1.07797', 'c': '1.07875'}, 'mid': {'o': '1.07836', 'h': '1.07912', 'l': '1.07805', 'c': '1.07883'}, 'ask': {'o': '1.07844', 'h': '1.07920', 'l': '1.07813', 'c': '1.07891'}}
{'complete': True, 'volume': 3232, 'time': '2024-02-02T19:00:00.000000000Z', 'bid': {'o': '1.07874', 'h': '1.07952', 'l': '1.07854', 'c': '1.07918'}, 'mid': {'o': '1.07882', 'h': '1.07959', 'l': '1.07862', 'c': '1.07926'}, 'ask': {'o': '1.07889', 'h': '1.07966', 'l': '1.07869', 'c': '1.07934'}}
{'complete': True, 'volume': 2937, 'time': '2024-02-02T20:00:00.000000000Z', 'bid': {'o': '1.07919', 'h': '1.07967', 'l': '1.07913', 'c': '1.07925'}, 'mid': {'o': '1.07926', 'h': '1.07974', 'l': '1.07920', 'c': '1.07932'}, 'ask': {'o': '1.07933', 'h': '1.07982', 'l': '1.07928', 'c': '1.07939'}}
{'complete': True, 'volume': 1975, 'time': '2024-02-02T21:00:00.000000000Z', 'bid': {'o': '1.07924', 'h': '1.07934', 'l': '1.07819', 'c': '1.07844'}, 'mid': {'o': '1.07932', 'h': '1.07942', 'l': '1.07854', 'c': '1.07870'}, 'ask': {'o': '1.07939', 'h': '1.07950', 'l': '1.07874', 'c': '1.07897'}}

In [17]:
prices = ['mid', 'bid', 'ask']
ohlc = ['o', 'h', 'l', 'c']

In [22]:
our_data = []
for candle in data['candles']:
    if candle['complete'] == False:
        continue
    new_dict = {
        'time': candle['time'],
        'volume': candle['volume']
    }
    for price in prices:
        for oh in ohlc:
            new_dict[f'{price}_{oh}'] = candle[price][oh]
    our_data.append(new_dict)
print(our_data[0])

{'time': '2024-02-02T12:00:00.000000000Z', 'volume': 2792, 'mid_o': '1.08838', 'mid_h': '1.08852', 'mid_l': '1.08776', 'mid_c': '1.08804', 'bid_o': '1.08831', 'bid_h': '1.08844', 'bid_l': '1.08769', 'bid_c': '1.08797', 'ask_o': '1.08845', 'ask_h': '1.08859', 'ask_l': '1.08784', 'ask_c': '1.08811'}

In [26]:
candles_df = pd.DataFrame.from_dict(our_data)
candles_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2024-02-02T12:00:00.000000000Z,2792,1.08838,1.08852,1.08776,1.08804,1.08831,1.08844,1.08769,1.08797,1.08845,1.08859,1.08784,1.08811
1,2024-02-02T13:00:00.000000000Z,11299,1.08807,1.08861,1.08038,1.08072,1.08800,1.08854,1.08031,1.08064,1.08814,1.08868,1.08045,1.08079
2,2024-02-02T14:00:00.000000000Z,11472,1.08074,1.08170,1.07916,1.08089,1.08067,1.08163,1.07908,1.08078,1.08081,1.08178,1.07923,1.08100
3,2024-02-02T15:00:00.000000000Z,10559,1.08078,1.08113,1.07831,1.08024,1.08070,1.08106,1.07824,1.08017,1.08085,1.08124,1.07838,1.08031
4,2024-02-02T16:00:00.000000000Z,6530,1.08026,1.08038,1.07824,1.07862,1.08019,1.08031,1.07817,1.07854,1.08033,1.08045,1.07831,1.07869
5,2024-02-02T17:00:00.000000000Z,5032,1.07863,1.07926,1.07808,1.07834,1.07855,1.07919,1.07800,1.07827,1.07871,1.07933,1.07815,1.07842
6,2024-02-02T18:00:00.000000000Z,4502,1.07836,1.07912,1.07805,1.07883,1.07828,1.07905,1.07797,1.07875,1.07844,1.07920,1.07813,1.07891
7,2024-02-02T19:00:00.000000000Z,3232,1.07882,1.07959,1.07862,1.07926,1.07874,1.07952,1.07854,1.07918,1.07889,1.07966,1.07869,1.07934
8,2024-02-02T20:00:00.000000000Z,2937,1.07926,1.07974,1.07920,1.07932,1.07919,1.07967,1.07913,1.07925,1.07933,1.07982,1.07928,1.07939
9,2024-02-02T21:00:00.000000000Z,1975,1.07932,1.07942,1.07854,1.07870,1.07924,1.07934,1.07819,1.07844,1.07939,1.07950,1.07874,1.07897

In [27]:
candles_df.to_pickle('EUR_USD_H1.pkl')

In [28]:
test_df = pd.read_pickle('EUR_USD_H1.pkl')
test_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2024-02-02T12:00:00.000000000Z,2792,1.08838,1.08852,1.08776,1.08804,1.08831,1.08844,1.08769,1.08797,1.08845,1.08859,1.08784,1.08811
1,2024-02-02T13:00:00.000000000Z,11299,1.08807,1.08861,1.08038,1.08072,1.08800,1.08854,1.08031,1.08064,1.08814,1.08868,1.08045,1.08079
2,2024-02-02T14:00:00.000000000Z,11472,1.08074,1.08170,1.07916,1.08089,1.08067,1.08163,1.07908,1.08078,1.08081,1.08178,1.07923,1.08100
3,2024-02-02T15:00:00.000000000Z,10559,1.08078,1.08113,1.07831,1.08024,1.08070,1.08106,1.07824,1.08017,1.08085,1.08124,1.07838,1.08031
4,2024-02-02T16:00:00.000000000Z,6530,1.08026,1.08038,1.07824,1.07862,1.08019,1.08031,1.07817,1.07854,1.08033,1.08045,1.07831,1.07869
5,2024-02-02T17:00:00.000000000Z,5032,1.07863,1.07926,1.07808,1.07834,1.07855,1.07919,1.07800,1.07827,1.07871,1.07933,1.07815,1.07842
6,2024-02-02T18:00:00.000000000Z,4502,1.07836,1.07912,1.07805,1.07883,1.07828,1.07905,1.07797,1.07875,1.07844,1.07920,1.07813,1.07891
7,2024-02-02T19:00:00.000000000Z,3232,1.07882,1.07959,1.07862,1.07926,1.07874,1.07952,1.07854,1.07918,1.07889,1.07966,1.07869,1.07934
8,2024-02-02T20:00:00.000000000Z,2937,1.07926,1.07974,1.07920,1.07932,1.07919,1.07967,1.07913,1.07925,1.07933,1.07982,1.07928,1.07939
9,2024-02-02T21:00:00.000000000Z,1975,1.07932,1.07942,1.07854,1.07870,1.07924,1.07934,1.07819,1.07844,1.07939,1.07950,1.07874,1.07897